package:
    name: eko
    version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_DESCRIBE_NUMBER }}+{{ GIT_DESCRIBE_HASH }}"

source:
    git_url: ../

requirements:
    build:
        - {{ compiler("c") }}
    host:
        - numpy
        - python
        - numba
        - scipy      
        - cffi
        - gsl
    run:
        - numpy
        - python
        - numba
        - sphinx # documentation
        - recommonmark
        - sphinx_rtd_theme
        - scipy
        - cffi
        - gsl

test:
    requires:
        - hypothesis
        - pytest
        - coverage

    source_files:
        - "*"

build:
    number: 0
    detect_binary_files_with_prefix: True
    # import CONDA_BUILD_SYSROOT from env variable for osx
    script_env:
      - CONDA_BUILD_SYSROOT # [osx]

about:
    home: https://github.com/N3PDF/eko
    license: GPLv3
    summary: "Evolution kernel operator"
