name: eko

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgsl-dev
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with pylint
      run: |
        pip install pylint
        # Search for actual errors
        pylint src/*/*.py -E
        # For warnings instead return always zero
        pylint src/*/*.py --exit-zero
    - name: Test with pytest
      run: |
        pip install pytest
        # until https://github.com/numba/numba/pull/5660 is confirmed we need to deactivate numba prior running
        export NUMBA_DISABLE_JIT=1
        pip install pytest-cov
        pytest
